/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerCadastraCliente;

/**
 *
 * @author marci
 */
public class CadastrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form jcliente
     */
    public CadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        CCC1 = new javax.swing.JLabel();
        CCC2 = new javax.swing.JLabel();
        CCC6 = new javax.swing.JLabel();
        CCC7 = new javax.swing.JLabel();
        CCC8 = new javax.swing.JLabel();
        CCC9 = new javax.swing.JLabel();
        CCC10 = new javax.swing.JLabel();
        CCC11 = new javax.swing.JLabel();
        CCC12 = new javax.swing.JLabel();
        CCC13 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textCPF = new javax.swing.JTextField();
        textRG = new javax.swing.JTextField();
        textCNH = new javax.swing.JTextField();
        textEndereco = new javax.swing.JTextField();
        textCidade = new javax.swing.JTextField();
        textUF = new javax.swing.JTextField();
        textDDI = new javax.swing.JTextField();
        textDDD = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        textDataDia = new javax.swing.JTextField();
        textDataMes = new javax.swing.JTextField();
        textDataAno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        CCC1.setText("CADASTRO DE CLIENTE");
        getContentPane().add(CCC1);
        CCC1.setBounds(140, 10, 160, 14);

        CCC2.setText("Nome:");
        getContentPane().add(CCC2);
        CCC2.setBounds(10, 30, 40, 14);

        CCC6.setText("CPF:");
        getContentPane().add(CCC6);
        CCC6.setBounds(10, 70, 40, 14);

        CCC7.setText("RG:");
        getContentPane().add(CCC7);
        CCC7.setBounds(10, 100, 40, 14);

        CCC8.setText("CNH:");
        getContentPane().add(CCC8);
        CCC8.setBounds(10, 130, 40, 14);

        CCC9.setText("Data de Nascimento:");
        getContentPane().add(CCC9);
        CCC9.setBounds(160, 80, 110, 14);

        CCC10.setText("Endereço:");
        getContentPane().add(CCC10);
        CCC10.setBounds(10, 160, 49, 14);

        CCC11.setText("Cidade:");
        getContentPane().add(CCC11);
        CCC11.setBounds(10, 190, 50, 14);

        CCC12.setText("UF:");
        getContentPane().add(CCC12);
        CCC12.setBounds(320, 190, 30, 14);

        CCC13.setText("Telefone(DDI+DDD):");
        getContentPane().add(CCC13);
        CCC13.setBounds(20, 250, 130, 14);

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });
        getContentPane().add(textNome);
        textNome.setBounds(60, 30, 360, 30);
        getContentPane().add(textCPF);
        textCPF.setBounds(60, 60, 100, 30);

        textRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRGActionPerformed(evt);
            }
        });
        getContentPane().add(textRG);
        textRG.setBounds(60, 90, 100, 30);
        getContentPane().add(textCNH);
        textCNH.setBounds(60, 120, 360, 30);
        getContentPane().add(textEndereco);
        textEndereco.setBounds(60, 150, 360, 30);
        getContentPane().add(textCidade);
        textCidade.setBounds(60, 180, 250, 30);
        getContentPane().add(textUF);
        textUF.setBounds(340, 180, 80, 30);

        textDDI.setText("DDI");
        textDDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDDIActionPerformed(evt);
            }
        });
        getContentPane().add(textDDI);
        textDDI.setBounds(140, 240, 40, 30);

        textDDD.setText("DDD");
        getContentPane().add(textDDD);
        textDDD.setBounds(190, 240, 40, 30);
        getContentPane().add(textTelefone);
        textTelefone.setBounds(250, 240, 170, 30);

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOK);
        buttonOK.setBounds(240, 280, 90, 30);

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancelar);
        buttonCancelar.setBounds(335, 280, 90, 30);
        getContentPane().add(textDataDia);
        textDataDia.setBounds(260, 70, 40, 30);

        textDataMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataMesActionPerformed(evt);
            }
        });
        getContentPane().add(textDataMes);
        textDataMes.setBounds(320, 70, 40, 30);
        getContentPane().add(textDataAno);
        textDataAno.setBounds(380, 70, 40, 30);

        jLabel2.setText("/");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 80, 34, 14);

        jLabel3.setText("/");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 80, 34, 14);

        setBounds(0, 0, 461, 371);
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRGActionPerformed

    private void textDDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDDIActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        ControllerCadastraCliente controller = new ControllerCadastraCliente();
        controller.atribuiDadosCliente(this.textNome.getText(),
                                       this.textCPF.getText(), 
                                       this.textRG.getText(), 
                                       this.textCNH.getText(), 
                                       this.textEndereco.getText(), 
                                       this.textCidade.getText(), 
                                       this.textUF.getText(), 
                                       this.textDDI.getText(), 
                                       this.textDDD.getText(), 
                                       this.textTelefone.getText(), 
                                       this.textDataDia.getText(), 
                                       this.textDataMes.getText(), 
                                       this.textDataAno.getText()
                                      );
        
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void textDataMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCC1;
    private javax.swing.JLabel CCC10;
    private javax.swing.JLabel CCC11;
    private javax.swing.JLabel CCC12;
    private javax.swing.JLabel CCC13;
    private javax.swing.JLabel CCC2;
    private javax.swing.JLabel CCC6;
    private javax.swing.JLabel CCC7;
    private javax.swing.JLabel CCC8;
    private javax.swing.JLabel CCC9;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textCNH;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textDDD;
    private javax.swing.JTextField textDDI;
    private javax.swing.JTextField textDataAno;
    private javax.swing.JTextField textDataDia;
    private javax.swing.JTextField textDataMes;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textRG;
    private javax.swing.JTextField textTelefone;
    private javax.swing.JTextField textUF;
    // End of variables declaration//GEN-END:variables
}
