/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerCadastraFuncionario;
import javax.swing.JOptionPane;

/**
 *
 * @author marci
 */
public class CadastraFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form jcliente
     */
    public CadastraFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        CCC1 = new javax.swing.JLabel();
        CCC2 = new javax.swing.JLabel();
        CCC6 = new javax.swing.JLabel();
        CCC7 = new javax.swing.JLabel();
        CCC8 = new javax.swing.JLabel();
        CCC9 = new javax.swing.JLabel();
        CCC10 = new javax.swing.JLabel();
        CCC11 = new javax.swing.JLabel();
        CCC12 = new javax.swing.JLabel();
        CCC13 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textCPF = new javax.swing.JTextField();
        textRG = new javax.swing.JTextField();
        textCNH = new javax.swing.JTextField();
        textEndereco = new javax.swing.JTextField();
        textCidade = new javax.swing.JTextField();
        textUF = new javax.swing.JTextField();
        textDDI = new javax.swing.JTextField();
        textDDD = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        SADB = new javax.swing.JLabel();
        textMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        textDataDia = new javax.swing.JTextField();
        textDataAno = new javax.swing.JTextField();
        textDataMes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        CCC1.setText("CADASTRO DE FUNCIONARIO");
        getContentPane().add(CCC1);
        CCC1.setBounds(140, 10, 210, 14);

        CCC2.setText("Nome:");
        getContentPane().add(CCC2);
        CCC2.setBounds(10, 70, 40, 14);

        CCC6.setText("CPF:");
        getContentPane().add(CCC6);
        CCC6.setBounds(10, 100, 40, 14);

        CCC7.setText("RG:");
        getContentPane().add(CCC7);
        CCC7.setBounds(10, 130, 40, 14);

        CCC8.setText("CNH:");
        getContentPane().add(CCC8);
        CCC8.setBounds(10, 160, 40, 14);

        CCC9.setText("Data de Nascimento:");
        getContentPane().add(CCC9);
        CCC9.setBounds(170, 130, 110, 14);

        CCC10.setText("Endereço:");
        getContentPane().add(CCC10);
        CCC10.setBounds(10, 190, 49, 14);

        CCC11.setText("Cidade:");
        getContentPane().add(CCC11);
        CCC11.setBounds(10, 220, 50, 14);

        CCC12.setText("UF:");
        getContentPane().add(CCC12);
        CCC12.setBounds(10, 250, 30, 14);

        CCC13.setText("Telefone(DDI+DDD):");
        getContentPane().add(CCC13);
        CCC13.setBounds(20, 280, 130, 14);

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });
        getContentPane().add(textNome);
        textNome.setBounds(60, 60, 350, 30);
        getContentPane().add(textCPF);
        textCPF.setBounds(60, 90, 100, 30);

        textRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRGActionPerformed(evt);
            }
        });
        getContentPane().add(textRG);
        textRG.setBounds(60, 120, 100, 30);
        getContentPane().add(textCNH);
        textCNH.setBounds(60, 150, 100, 30);
        getContentPane().add(textEndereco);
        textEndereco.setBounds(60, 180, 340, 30);
        getContentPane().add(textCidade);
        textCidade.setBounds(60, 210, 80, 30);
        getContentPane().add(textUF);
        textUF.setBounds(60, 240, 40, 30);

        textDDI.setText("DDI");
        textDDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDDIActionPerformed(evt);
            }
        });
        getContentPane().add(textDDI);
        textDDI.setBounds(140, 270, 40, 30);

        textDDD.setText("DDD");
        getContentPane().add(textDDD);
        textDDD.setBounds(190, 270, 40, 30);
        getContentPane().add(textTelefone);
        textTelefone.setBounds(250, 270, 150, 30);

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOK);
        buttonOK.setBounds(240, 310, 79, 30);

        SADB.setText("Codigo de Matricula:");
        getContentPane().add(SADB);
        SADB.setBounds(10, 30, 180, 14);

        textMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(textMatricula);
        textMatricula.setBounds(120, 30, 290, 30);

        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 220, 80, 20);

        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 250, 34, 20);
        getContentPane().add(textLogin);
        textLogin.setBounds(250, 210, 150, 30);
        getContentPane().add(senha);
        senha.setBounds(250, 240, 150, 30);
        getContentPane().add(textDataDia);
        textDataDia.setBounds(280, 120, 40, 30);
        getContentPane().add(textDataAno);
        textDataAno.setBounds(400, 120, 40, 30);
        getContentPane().add(textDataMes);
        textDataMes.setBounds(340, 120, 40, 30);

        jLabel3.setText("/");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 130, 34, 14);

        jLabel4.setText("/");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 130, 34, 14);

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancelar);
        buttonCancelar.setBounds(330, 310, 80, 30);

        setBounds(0, 0, 461, 377);
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRGActionPerformed

    private void textDDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDDIActionPerformed

    private void textMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatriculaActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        ControllerCadastraFuncionario controller = new ControllerCadastraFuncionario();
        
        controller.atribuiDadosFuncionario(this.textMatricula.getText(), 
                                           this.textNome.getText(), 
                                           this.textCPF.getText(), 
                                           this.textRG.getText(), 
                                           this.textCNH.getText(), 
                                           this.textEndereco.getText(), 
                                           this.textCidade.getText(), 
                                           this.textUF.getText(), 
                                           this.textDDD.getText(), 
                                           this.textDDI.getText(), 
                                           this.textTelefone.getText(), 
                                           this.textDataDia.getText(),
                                           this.textDataMes.getText(), 
                                           this.textDataAno.getText(), 
                                           this.textLogin.getText(), 
                                           this.senha.getText()
        );
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCC1;
    private javax.swing.JLabel CCC10;
    private javax.swing.JLabel CCC11;
    private javax.swing.JLabel CCC12;
    private javax.swing.JLabel CCC13;
    private javax.swing.JLabel CCC2;
    private javax.swing.JLabel CCC6;
    private javax.swing.JLabel CCC7;
    private javax.swing.JLabel CCC8;
    private javax.swing.JLabel CCC9;
    private javax.swing.JLabel SADB;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField textCNH;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textDDD;
    private javax.swing.JTextField textDDI;
    private javax.swing.JTextField textDataAno;
    private javax.swing.JTextField textDataDia;
    private javax.swing.JTextField textDataMes;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textRG;
    private javax.swing.JTextField textTelefone;
    private javax.swing.JTextField textUF;
    // End of variables declaration//GEN-END:variables
}
