/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerCadastraCarro;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.dao.DAOTipoCarro;

/**
 *
 * @author marci
 */
public class CadastrarCarro extends javax.swing.JInternalFrame {

    /**
     * Creates new form jcarro
     */
    public CadastrarCarro() {
        initComponents();
        populaComboTipo();
    }
    
    public void populaComboTipo(){
        DAOTipoCarro dao = new DAOTipoCarro();
        ArrayList lista = dao.listarTipos();
        
        for(int i = 0; i < lista.size(); i++){
            comboTipoCarro.addItem((String) lista.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CC2 = new javax.swing.JLabel();
        CC4 = new javax.swing.JLabel();
        CC5 = new javax.swing.JLabel();
        CC6 = new javax.swing.JLabel();
        CC7 = new javax.swing.JLabel();
        CC8 = new javax.swing.JLabel();
        CC9 = new javax.swing.JLabel();
        CC10 = new javax.swing.JLabel();
        textUF = new javax.swing.JTextField();
        textModelo = new javax.swing.JTextField();
        textMarca = new javax.swing.JTextField();
        textCor = new javax.swing.JTextField();
        textCidade = new javax.swing.JTextField();
        textPlaca = new javax.swing.JTextField();
        CC12 = new javax.swing.JLabel();
        buttonOK = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        textAno = new javax.swing.JTextField();
        comboTipoCarro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        textValor = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(343, 350));
        setMinimumSize(new java.awt.Dimension(343, 350));
        getContentPane().setLayout(null);

        CC2.setText("Placa:");
        getContentPane().add(CC2);
        CC2.setBounds(170, 60, 37, 10);

        CC4.setText("Tipo:");
        getContentPane().add(CC4);
        CC4.setBounds(20, 240, 40, 14);

        CC5.setText("Ano:");
        getContentPane().add(CC5);
        CC5.setBounds(170, 90, 50, 10);

        CC6.setText("Modelo:");
        getContentPane().add(CC6);
        CC6.setBounds(20, 150, 50, 14);

        CC7.setText("Marca:");
        getContentPane().add(CC7);
        CC7.setBounds(20, 180, 50, 14);

        CC8.setText("Cor:");
        getContentPane().add(CC8);
        CC8.setBounds(20, 210, 40, 14);

        CC9.setText("UF:");
        getContentPane().add(CC9);
        CC9.setBounds(20, 60, 60, 14);

        CC10.setText("Cidade:");
        getContentPane().add(CC10);
        CC10.setBounds(20, 90, 70, 14);

        textUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUFActionPerformed(evt);
            }
        });
        getContentPane().add(textUF);
        textUF.setBounds(70, 50, 90, 30);

        textModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textModeloActionPerformed(evt);
            }
        });
        getContentPane().add(textModelo);
        textModelo.setBounds(80, 140, 190, 30);

        textMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(textMarca);
        textMarca.setBounds(80, 170, 190, 30);

        textCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCorActionPerformed(evt);
            }
        });
        getContentPane().add(textCor);
        textCor.setBounds(80, 200, 190, 30);

        textCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(textCidade);
        textCidade.setBounds(70, 80, 90, 30);

        textPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(textPlaca);
        textPlaca.setBounds(200, 50, 80, 30);

        CC12.setText("Cadastro de carro");
        getContentPane().add(CC12);
        CC12.setBounds(120, 10, 180, 20);

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOK);
        buttonOK.setBounds(60, 300, 110, 30);

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancelar);
        buttonCancelar.setBounds(180, 300, 110, 30);

        textAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAnoActionPerformed(evt);
            }
        });
        getContentPane().add(textAno);
        textAno.setBounds(200, 80, 80, 30);

        comboTipoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoCarroActionPerformed(evt);
            }
        });
        getContentPane().add(comboTipoCarro);
        comboTipoCarro.setBounds(80, 230, 190, 30);

        jLabel1.setText("Valor do Aluguel: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 270, 90, 14);
        getContentPane().add(textValor);
        textValor.setBounds(120, 260, 150, 30);

        setBounds(0, 0, 323, 385);
    }// </editor-fold>//GEN-END:initComponents

    private void textUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUFActionPerformed

    private void textModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textModeloActionPerformed

    private void textMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMarcaActionPerformed

    private void textCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCorActionPerformed

    private void textCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCidadeActionPerformed

    private void textPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPlacaActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        ControllerCadastraCarro controller = new ControllerCadastraCarro();
        controller.associaDadosCarro(this.textUF.getText(), 
                                     this.textCidade.getText(), 
                                     this.textPlaca.getText(),
                                     this.textAno.getText(), 
                                     this.textModelo.getText(), 
                                     this.textMarca.getText(), 
                                     this.textCor.getText(), 
                                     this.comboTipoCarro.getSelectedItem()+"",
                                     this.textValor.getText());
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void textAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAnoActionPerformed

    private void comboTipoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoCarroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboTipoCarroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CC10;
    private javax.swing.JLabel CC12;
    private javax.swing.JLabel CC2;
    private javax.swing.JLabel CC4;
    private javax.swing.JLabel CC5;
    private javax.swing.JLabel CC6;
    private javax.swing.JLabel CC7;
    private javax.swing.JLabel CC8;
    private javax.swing.JLabel CC9;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonOK;
    private javax.swing.JComboBox<String> comboTipoCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textAno;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textCor;
    private javax.swing.JTextField textMarca;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textPlaca;
    private javax.swing.JTextField textUF;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
}
