/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerMostruarioFuncionario;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.DAOFuncionario;
import model.vo.Funcionario;

/**
 *
 * @author WIN 7
 */
public class MostruarioFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form JMostruario
     */
    
    
    public MostruarioFuncionario() {
        initComponents();
        populaTabela();
    }
    
    public void populaTabela(){
        DAOFuncionario dao = new DAOFuncionario();
        ArrayList lista = dao.listaFuncionarios();
        Funcionario[] funcionario = new Funcionario[lista.size()];
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
        
        for(int i = 0; i < lista.size(); i++){
            funcionario[i] = dao.consultaFuncionario((int)lista.get(i));
            model.addRow(new Object[]{funcionario[i].getFuncNm(), funcionario[i].getFuncCod(), funcionario[i].getFuncMatrCod(), funcionario[i].getFuncLogin()});
        }
    }
    
    public void insereFormulario(){
        DAOFuncionario dao = new DAOFuncionario();
        Funcionario funcionario = new Funcionario();
        
        int seleciona = tabelaFuncionarios.getSelectedRow();
        int codigo    = parseInt(tabelaFuncionarios.getModel().getValueAt(seleciona, 1).toString());
        
        funcionario = dao.consultaFuncionario(codigo);
        
        Date dataNasc = funcionario.getFuncNascDt();
        int ano = 1900 + dataNasc.getYear();
        int mes = dataNasc.getMonth();
        int dia = dataNasc.getDate();
        
        this.textCod.setText(funcionario.getFuncCod()+"");
        //nome
        this.textNome.setText(funcionario.getFuncNm());
        //cpf
        this.textCPF.setText(funcionario.getFuncCPF());
        //rg
        this.textRG.setText(funcionario.getFuncRG());
        //cnh
        this.textCNH.setText(funcionario.getFuncCNH());
        //dataNasc
        this.textDataDia.setText(dia+"");
        this.textDataMes.setText(mes+"");
        this.textDataAno.setText(ano+"");
        //Endereço
        this.textEndereco.setText(funcionario.getFuncEndDs());
        //Cidade
        this.textCidade.setText(funcionario.getFuncCidDs());
        //uf
        this.textUF.setText(funcionario.getFuncUf());
        //telefone
        this.textDDD.setText(funcionario.getFuncTelefoneDDD());
        this.textDDI.setText(funcionario.getFuncTelefoneDDI());
        this.textTelefone.setText(funcionario.getFuncTelefoneDs());
        //
        this.textMatricula.setText(funcionario.getFuncMatrCod());
        this.textSenha.setText(funcionario.getFuncSenha());
        this.textLogin.setText(funcionario.getFuncLogin());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CCC2 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        CCC6 = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();
        CCC9 = new javax.swing.JLabel();
        textDataDia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textDataMes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textDataAno = new javax.swing.JTextField();
        CCC7 = new javax.swing.JLabel();
        textRG = new javax.swing.JTextField();
        CCC8 = new javax.swing.JLabel();
        textCNH = new javax.swing.JTextField();
        CCC10 = new javax.swing.JLabel();
        textEndereco = new javax.swing.JTextField();
        CCC11 = new javax.swing.JLabel();
        textCidade = new javax.swing.JTextField();
        CCC12 = new javax.swing.JLabel();
        textUF = new javax.swing.JTextField();
        CCC13 = new javax.swing.JLabel();
        textDDI = new javax.swing.JTextField();
        textDDD = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        buttonFechar = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        textCod = new javax.swing.JTextField();
        textMatricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setAlignmentX(5.0F);
        setAlignmentY(5.0F);
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(827, 353));
        setMinimumSize(new java.awt.Dimension(827, 353));
        setNextFocusableComponent(this);
        setPreferredSize(new java.awt.Dimension(827, 353));

        jLabel1.setText("Mostruário");

        CCC2.setText("Nome:");

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        CCC6.setText("CPF:");

        CCC9.setText("Data de Nascimento:");

        jLabel2.setText("/");

        textDataMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataMesActionPerformed(evt);
            }
        });

        jLabel3.setText("/");

        CCC7.setText("RG:");

        textRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRGActionPerformed(evt);
            }
        });

        CCC8.setText("CNH:");

        CCC10.setText("Endereço:");

        CCC11.setText("Cidade:");

        CCC12.setText("UF:");

        CCC13.setText("Telefone(DDI+DDD):");

        textDDI.setText("+55");
        textDDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDDIActionPerformed(evt);
            }
        });

        textDDD.setText("DDD");

        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        tabelaFuncionarios.setBorder(new javax.swing.border.MatteBorder(null));
        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código", "Matricula", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaFuncionarios);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel4.setText("ID");

        textCod.setEnabled(false);

        jLabel5.setText("Matrícula");

        jLabel6.setText("Senha");

        jLabel7.setText("Login");

        textLogin.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CCC7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textRG, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CCC8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCNH, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(CCC13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(255, 255, 255)
                                        .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(textDDI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAlterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonFechar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CCC9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDataDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDataMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCC10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEndereco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CCC2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCC6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCPF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CCC11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCC12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAlterar, buttonExcluir, buttonFechar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CCC2)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CCC6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCC7)
                    .addComponent(CCC8)
                    .addComponent(textCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textDataDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(textDataMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(CCC9)
                        .addComponent(textEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CCC10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCC11)
                    .addComponent(CCC13)
                    .addComponent(textDDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCC12)
                    .addComponent(textUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlterar)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonFechar)
                    .addComponent(jLabel4)
                    .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        setBounds(25, 250, 827, 441);
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textDataMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataMesActionPerformed

    private void textRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRGActionPerformed

    private void textDDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDDIActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        // TODO add your handling code here:
        DAOFuncionario dao = new DAOFuncionario();
        Funcionario funcionario = new Funcionario();
        
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
  
        int seleciona = tabelaFuncionarios.getSelectedRow();
        int codigo    = parseInt(tabelaFuncionarios.getModel().getValueAt(seleciona, 1).toString());
        
        int linhas = model.getRowCount();
        if(linhas > 1){
            dao.removeFuncionario(codigo);
            linhas = model.getRowCount();
        
            if (linhas  > 0){
                for (int i = 0; i < linhas; i++){
                    model.removeRow(0);
                }            
            }
            populaTabela();
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "É necessário ao menos um funcionário.");
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void tabelaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionariosMouseClicked
        // TODO add your handling code here:
        insereFormulario();
    }//GEN-LAST:event_tabelaFuncionariosMouseClicked

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        // TODO add your handling code here:
        ControllerMostruarioFuncionario controller = new ControllerMostruarioFuncionario();
        
        controller.atribuiDadosAlterar(
                                    //String id,
                                    this.textCod.getText(),
                                    //String nome,
                                    this.textNome.getText(),
                                    //String cpf,
                                    this.textCPF.getText(),
                                    //String rg,
                                    this.textRG.getText(),
                                    //String cnh,
                                    this.textCNH.getText(),
                                    //String endereco,
                                    this.textEndereco.getText(),
                                    //String cidade,
                                    this.textCidade.getText(),
                                    //String uf,
                                    this.textUF.getText(),
                                    //String ddi,
                                    this.textDDI.getText(),
                                    //String ddd,
                                    this.textDDD.getText(),
                                    //String telefone,
                                    this.textTelefone.getText(),
                                    //String dataNascDia,
                                    this.textDataDia.getText(),
                                    //String dataNascMes,
                                    this.textDataMes.getText(),
                                    //String dataNascAno
                                    this.textDataAno.getText(),
                                    //String dataNascMes,
                                    this.textMatricula.getText(),
                                    //String dataNascAno
                                    this.textSenha.getText(),
                                    this.textLogin.getText()
                            );
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
        int linhas = model.getRowCount();
        
        if (linhas  > 0){
            for (int i = 0; i < linhas; i++){
                model.removeRow(0);
            }            
        }
        populaTabela();
    }//GEN-LAST:event_buttonAlterarActionPerformed

    int idFuncionarioSelecionado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCC10;
    private javax.swing.JLabel CCC11;
    private javax.swing.JLabel CCC12;
    private javax.swing.JLabel CCC13;
    private javax.swing.JLabel CCC2;
    private javax.swing.JLabel CCC6;
    private javax.swing.JLabel CCC7;
    private javax.swing.JLabel CCC8;
    private javax.swing.JLabel CCC9;
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JTextField textCNH;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textCod;
    private javax.swing.JTextField textDDD;
    private javax.swing.JTextField textDDI;
    private javax.swing.JTextField textDataAno;
    private javax.swing.JTextField textDataDia;
    private javax.swing.JTextField textDataMes;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textRG;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextField textTelefone;
    private javax.swing.JTextField textUF;
    // End of variables declaration//GEN-END:variables
}
