/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author WIN 7
 */
public class TelaPrincipalFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form telaprincipalcliente
     */
    public TelaPrincipalFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionario = new javax.swing.JMenu();
        menuFuncionariosCadastroCarro = new javax.swing.JMenuItem();
        cadastrarCliente = new javax.swing.JMenuItem();
        cadastrarFuncionario = new javax.swing.JMenuItem();
        listarCarros = new javax.swing.JMenuItem();
        listarClientes = new javax.swing.JMenuItem();
        listarFuncionarios = new javax.swing.JMenuItem();
        listaEspera = new javax.swing.JMenuItem();
        menuPessoa = new javax.swing.JMenu();
        pessoaCadastroCliente = new javax.swing.JMenuItem();
        pessoaCadastroFuncionarios = new javax.swing.JMenuItem();
        menuAltera = new javax.swing.JMenu();
        alteraCliente = new javax.swing.JMenuItem();
        alteraFuncionario = new javax.swing.JMenuItem();
        alteraCarro = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        sairmenu = new javax.swing.JRadioButtonMenuItem();
        sairprograma = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1077, 524, 524, 524));
        setMinimumSize(new java.awt.Dimension(1077, 524));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1080, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-90, -150, 1600, 1200);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        menuFuncionario.setText("Funcionários");

        menuFuncionariosCadastroCarro.setText("Cadastro de Carro");
        menuFuncionariosCadastroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosCadastroCarroActionPerformed(evt);
            }
        });
        menuFuncionario.add(menuFuncionariosCadastroCarro);

        cadastrarCliente.setText("Cadastro de Cliente");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        menuFuncionario.add(cadastrarCliente);

        cadastrarFuncionario.setText("Cadastro de Funcionario");
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(cadastrarFuncionario);

        listarCarros.setText("Listar Carros");
        menuFuncionario.add(listarCarros);

        listarClientes.setText("Listar Clientes");
        listarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarClientesActionPerformed(evt);
            }
        });
        menuFuncionario.add(listarClientes);

        listarFuncionarios.setText("Listar Funcionarios");
        listarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFuncionariosActionPerformed(evt);
            }
        });
        menuFuncionario.add(listarFuncionarios);

        listaEspera.setText("Lista de espera");
        menuFuncionario.add(listaEspera);

        jMenuBar1.add(menuFuncionario);

        menuPessoa.setText("Pessoa");

        pessoaCadastroCliente.setText("Cadastro de Cliente");
        pessoaCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaCadastroClienteActionPerformed(evt);
            }
        });
        menuPessoa.add(pessoaCadastroCliente);

        pessoaCadastroFuncionarios.setText("Cadastro de Funcionários");
        pessoaCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaCadastroFuncionariosActionPerformed(evt);
            }
        });
        menuPessoa.add(pessoaCadastroFuncionarios);

        jMenuBar1.add(menuPessoa);

        menuAltera.setText("Altera");

        alteraCliente.setText("Cliente");
        alteraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraClienteActionPerformed(evt);
            }
        });
        menuAltera.add(alteraCliente);

        alteraFuncionario.setText("Funcionário");
        alteraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraFuncionarioActionPerformed(evt);
            }
        });
        menuAltera.add(alteraFuncionario);

        alteraCarro.setText("Carro");
        alteraCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraCarroActionPerformed(evt);
            }
        });
        menuAltera.add(alteraCarro);

        jMenuBar1.add(menuAltera);

        menuSair.setText("Sair");

        sairmenu.setSelected(true);
        sairmenu.setText("Voltar para menu");
        sairmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairmenuActionPerformed(evt);
            }
        });
        menuSair.add(sairmenu);

        sairprograma.setSelected(true);
        sairprograma.setText("Sair do programa");
        sairprograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairprogramaActionPerformed(evt);
            }
        });
        menuSair.add(sairprograma);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1093, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairmenuActionPerformed
        TelaLogin tela1 = new TelaLogin();
        tela1.setVisible(true);
        dispose();
    }//GEN-LAST:event_sairmenuActionPerformed

    private void sairprogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairprogramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairprogramaActionPerformed

    private void menuFuncionariosCadastroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosCadastroCarroActionPerformed
        CadastrarCarro obj4=new CadastrarCarro();
         jDesktopPane1.add(obj4);
         obj4.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosCadastroCarroActionPerformed

    private void pessoaCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaCadastroClienteActionPerformed
      CadastrarCliente obj16=new CadastrarCliente();
      jDesktopPane1.add(obj16);
      obj16.setVisible(true);
// TODO add :your handling code her
    }//GEN-LAST:event_pessoaCadastroClienteActionPerformed

    private void alteraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraFuncionarioActionPerformed

    }//GEN-LAST:event_alteraFuncionarioActionPerformed

    private void pessoaCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaCadastroFuncionariosActionPerformed
        // TODO add your handling code here:
       CadastraFuncionario obj36=new CadastraFuncionario();
      jDesktopPane1.add(obj36);
      obj36.setVisible(true);
    }//GEN-LAST:event_pessoaCadastroFuncionariosActionPerformed

    private void alteraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_alteraClienteActionPerformed

    private void alteraCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraCarroActionPerformed

    }//GEN-LAST:event_alteraCarroActionPerformed

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        CadastraFuncionario obj3556 = new CadastraFuncionario();
        jDesktopPane1.add(obj3556);
        obj3556.setVisible(true);
        
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        // TODO add your handling code here:
        CadastrarCliente obj3556 = new CadastrarCliente();
        jDesktopPane1.add(obj3556);
        obj3556.setVisible(true);
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void listarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarClientesActionPerformed
        // TODO add your handling code here:
        MostruarioCliente obj3556 = new MostruarioCliente();
        jDesktopPane1.add(obj3556);
        obj3556.setVisible(true);
    }//GEN-LAST:event_listarClientesActionPerformed

    private void listarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFuncionariosActionPerformed
        // TODO add your handling code here:
        MostruarioFuncionario obj3556 = new MostruarioFuncionario();
        jDesktopPane1.add(obj3556);
        obj3556.setVisible(true);
    }//GEN-LAST:event_listarFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alteraCarro;
    private javax.swing.JMenuItem alteraCliente;
    private javax.swing.JMenuItem alteraFuncionario;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem cadastrarFuncionario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listaEspera;
    private javax.swing.JMenuItem listarCarros;
    private javax.swing.JMenuItem listarClientes;
    private javax.swing.JMenuItem listarFuncionarios;
    private javax.swing.JMenu menuAltera;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenuItem menuFuncionariosCadastroCarro;
    private javax.swing.JMenu menuPessoa;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem pessoaCadastroCliente;
    private javax.swing.JMenuItem pessoaCadastroFuncionarios;
    private javax.swing.JRadioButtonMenuItem sairmenu;
    private javax.swing.JRadioButtonMenuItem sairprograma;
    // End of variables declaration//GEN-END:variables
}
