/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerTelaLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN 7
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Telalogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAcessar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        buttonEntrarFuncionario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(502, 206, 206, 206));
        setMinimumSize(new java.awt.Dimension(502, 206));
        getContentPane().setLayout(null);

        buttonAcessar.setBackground(new java.awt.Color(204, 204, 204));
        buttonAcessar.setText("Acessar");
        buttonAcessar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        buttonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAcessar);
        buttonAcessar.setBounds(230, 130, 100, 21);

        buttonSair.setBackground(new java.awt.Color(204, 204, 204));
        buttonSair.setText("Sair");
        buttonSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSair);
        buttonSair.setBounds(340, 130, 100, 21);

        buttonEntrarFuncionario.setBackground(new java.awt.Color(204, 204, 204));
        buttonEntrarFuncionario.setText("Entrar");
        buttonEntrarFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        buttonEntrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEntrarFuncionario);
        buttonEntrarFuncionario.setBounds(80, 110, 90, 50);

        jLabel2.setText("Usuário:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 40, 80, 30);

        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 90, 50, 20);

        jLabel4.setText("Cliente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 50, 10);
        getContentPane().add(textUsuario);
        textUsuario.setBounds(240, 40, 200, 30);

        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textSenha);
        textSenha.setBounds(240, 80, 200, 30);

        jLabel5.setText("Funcionário");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 10, 90, 14);

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icone.jpg"))); // NOI18N
        imagem.setText("jLabel6");
        imagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(imagem);
        imagem.setBounds(10, 10, 160, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fundotelaLogin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 590, 490);

        setSize(new java.awt.Dimension(502, 206));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcessarActionPerformed
     TelaPrincipalFuncionario tela = new TelaPrincipalFuncionario();
     ControllerTelaLogin controller = new ControllerTelaLogin();
     
     int x = controller.atribuiDados(this.textUsuario.getText(), this.textSenha.getText());
     
     if(x > 0){
        tela.setVisible(true);
        dispose();
     }else{
         JOptionPane.showMessageDialog(null, "Senha ou usuário incorretos");
     }
     
     
    }//GEN-LAST:event_buttonAcessarActionPerformed

    private void buttonEntrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarFuncionarioActionPerformed
     TelaPrincipalCliente tela = new TelaPrincipalCliente();
     tela.setVisible(true);
     dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_buttonEntrarFuncionarioActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcessar;
    private javax.swing.JButton buttonEntrarFuncionario;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
